### ISSUE TITLE
Lock Ownership Model 

### ISSUE THREAD

**Issue by 65001** [hexcowboy/rslock#13] opened 2024-05-29 15:37 UTC
# Use Case

I'm trying to do is use the `LockManager`, to create a lock, and pass it to a tokio channel. 

Something like

```rust
let entry: T;
let lockManager = LockManager::new();
let lock = lockManager.lock();
channel.send( (entry, lock) );
```

# Issue

However rust is complaining that the `lockManager` will go out of scope. So I tried to send both the `lockManager` and the lock through the channel.

Changing the logic to

```rust
let entry: T;
let lockManager = Arc::new(LockManager::new());
let lock: Lock<'_> = lockManager.lock(..., ...);
channel.send( (entry, lock) );
```
does not work.

# Proposed Change

I think the developer experience could be improved if you did something like this:
```rust
pub struct Lock<'a> {
    /// The resource to lock. Will be used as the key in Redis.
    pub resource: Vec<u8>,
    /// The value for this lock.
    pub val: Vec<u8>,
    /// Time the lock is still valid.
    /// Should only be slightly smaller than the requested TTL.
    pub validity_time: usize,
    /// Used to limit the lifetime of a lock to its lock manager.
    pub lock_manager: Arc<LockManagerInner>,
}

pub struct LockManagerInner { 
...
}

pub struct LockManager { 
   pub lock_manager: Arc<LockManagerInner>
}
```
This would allow a channel responsible for creating locks, a channel for doing other stuff, and a channel for closing locks to be represented clearly without having to worry about lifetimes. 

This is the pattern that the [mongo](https://github.com/mongodb/mongo-rust-driver/blob/main/src/db.rs) driver for rust uses & it moves the complexity from the user to the crate.

Would you welcome a PR for this change?

**Comment by hexcowboy** [comment] 2024-06-05 23:58
hi, i'm trying to better understand. can you provide a fully reproducible code sample of the issue you're encountering? this code compiles fine

```rs
use rslock::LockManager;
use tokio::sync::mpsc;

#[tokio::main]
async fn main() {
    // Example entry type
    let entry: String = "example_entry".to_string();

    // Initialize your LockManager
    let lock_manager = LockManager::new(vec!["redis://127.0.0.1:6379"]);

    // Acquire the lock
    let lock = lock_manager.lock(b"resource", 1000).await.unwrap();

    // Send the lock and entry through the channel
    let (tx, mut rx) = mpsc::channel(32);
    tx.send((entry, lock)).await.unwrap();

    // Retrieve from channel and use
    if let Some((entry, lock)) = rx.recv().await {
        println!(
            "Got entry: {} with lock for resource: {:?}",
            entry, lock.resource
        );
    }
}
```

**Comment by 65001** [comment] 2024-06-07 03:54
I'm ingesting data from a Kafka topic, represented as a channel in Rust and need to acquire a lock on the given value, before modifying the value in redis/db, while still allowing other values to be processed concurrently.

In my production code, the function signature is a bit convoluted:
```rust
async fn stream<T: DeserializeOwned + Send + Sync + 'static + Debug + Clone, ...>(mut receiver: Receiver<T>, ...) {}
```
When I looked at your example, I thought the issue might have been the `static` lifetime requirement for T, but my simpler example is still throwing lifetime errors:

```rust
#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
struct ExampleStruct {
//Random data
}

async fn stream(mut receiver: Receiver<ExampleStruct>, lock_manager: LockManager) {
       //channel will be consumed by another spawned tokio thread, omitted for clarity
       let (tx, mut rx) = mpsc::channel(32);
        loop {
            match receiver.recv().await {
                Some(e) => {
                    let lock_managed = lock_manager.clone();
                    let sending = tx.clone();
                    
                    tokio::spawn(async move {
                        let l = lock_managed.lock(b"key", 10).await;
                        sending.send( (e, l) );
                    });

                }
                None => {}
            }
        }
    }
   
```

This is similar to what I'm going for and this is the error I get:
```
error[E0597]: `lock_managed` does not live long enough
let lock_managed = lock_manager.clone();
    |                         ------------ binding `lock_managed` declared here
    |                     let sending = tx.clone();
    |                         ------- lifetime `'1` appears in the type of `sending`
    |                     tokio::spawn(async move {
    |                         let l = lock_managed.lock(b"key", 10).await;
    |                                 ^^^^^^^^^^^^ borrowed value does not live long enough
    |                         sending.send( (e, l));
    |                         ---------------------- argument requires that `lock_managed` is borrowed for `'1`
    |                     });
    |                     - `lock_managed` dropped here while still borrowed
```

**Comment by hexcowboy** [comment] 2024-06-23 21:03
sorry for the delayed reply. @65001 this does seem like a nice dx improvement. i would welcome a PR for this, feel free to reach out if you have any questions

edit: it would also be nice if you could add a minimal example to the `examples` folder to show others how to send `lock_manager` over a channel

**Comment by 65001** [comment] 2024-06-24 04:46
@hexcowboy I tried a couple of ways, but I kept running into interior mutability issues that I couldn't figure out how to solve without reaching for `RefCell` or a very large rewrite.

However I think this issue, can also be solved by making the `Lock` have an optional reference to `LockManager`. 

In your `tokio-comp` code, you don't use the drop, so there's no need for Lock to have a reference back to `LockManager`. I copy and pasted the code and made those changes, which I also think solve the issue.

If you think there's a chance that the issue could come up in the async-std version, I can make a function that returns that type of lock, all the time.

I tested the code with both feature flags, and it seems to work fine. I made a PR: https://github.com/hexcowboy/rslock/pull/20

**Comment by hexcowboy** [comment] 2024-08-08 13:03
seems like there was an attempt to implement here https://github.com/hexcowboy/rslock/pull/20

closing this now as i'm not convinced this will solve the issue described

**Comment by mtfcd** [comment] 2024-08-13 08:45
I created a pr #22 that resolve this issure.
But I found that `Lock` can be cloned. If one thread clone it and send it to an other thread, one thread might think it still locked while it has been unlocked in the other thread. Should this be concerned? Maybe just remove the `Clone` derive?

**Comment by 65001** [comment] 2024-08-13 12:14
@mtfcd Having the lock manager produce a Arc<Lock> would or Arc<tokio::sync::RwLock<Lock>> would solve the issue of a thread believing its locked while another believes it's unlocked?

**Comment by mtfcd** [comment] 2024-08-13 12:37
Actually, unlock one lock twice in the same thread is also possible. because unlocking it only takes a &lock. So I wonder if it's intentional that the author want it can be unlocked multiple times.

**Comment by hexcowboy** [comment] 2024-08-20 15:52
@mtfcd It does not seem to me that `Lock` being `Clone` is intentional. In both a single and multi thread application it may not be harmful unless the application logic depends on all threads knowing that the lock is freed.

It would be good to remove `Clone` from `Lock`. It would also be good to track the lock state. I would suggest an `AtomicBool` instead of `RwLock` for this.

If you could add these changes to your PR I think this issue could be resolved.

**Comment by mtfcd** [comment] 2024-08-21 08:15
@hexcowboy  Added new commits as you suggested. But I'm not sure if this is the right way: `is_freed` is only set after `unlock` is called. I considerd also set it using expire time. But the time will alway be inaccurate due to network latency with redis server. Any other suggestions?

**Comment by hexcowboy** [comment] 2024-09-14 08:59
https://github.com/hexcowboy/rslock/releases/tag/v0.5.0

**Closed as completed by hexcowboy** 2024-09-14 08:59 UTC
